version: '2'

services:

    prometheus:
        image: prom/prometheus
        privileged: true
        volumes:
            - /vagrant/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - /vagrant/prometheus/rules:/alertmanager/rules
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    node-exporter:
        image: prom/node-exporter
        ports:
            - '9100:9100'

    alertmanager:
        restart: always
        privileged: true
        depends_on:
          - prometheus
        image: prom/alertmanager
        container_name: alertmanager
        volumes:
          - /vagrant/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        command:
            - '--config.file=/alertmanager.yml'
        ports:
            - '9093:9093'
