global:
  scrape_interval: 10s
  external_labels:
    monitor: 'DevOps-lab-monitor'

#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:['192.168.99.101:9093']
#    scheme: http
#    timeout: 10s

#rule_files:
#  - "rules/*.yml"
#  - '/alertmanager/rules'


scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.99.101:9323']
  - job_name: 'app goprom'
    static_configs:
    - targets: ['192.168.99.102:8081']
    - targets: ['192.168.99.103:8081']
  - job_name: 'node_explorer'
    static_configs:
      - targets: ['192.168.99.101:9100']
  - job_name: alertmanager
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
    - targets: ['192.168.99.101:9093']
